platform :ios, '6.0'

#pod 'SBJson'
pod 'TouchJSON'
pod 'ZipArchive'
pod 'Reachability'
pod 'RestKit'
pod 'RestKit/Testing'
pod 'RestKit/Search'
pod 'NoticeView'
pod 'Appirater'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'DTCoreText'
pod 'SVPullToRefresh'
pod 'ViewDeck', '= 2.2.11'
pod 'OpenUDID'
pod 'MGImageUtilities'
pod 'MGBox2'
pod 'EAIntroView'

pod 'QuickDialog'
pod 'QuickDialog/Extras'
