platform :ios, '5.0'

pod 'Reachability'
pod 'RestKit', '~> 0.20.0'
pod 'RestKit/Testing', '~>0.20.0'
pod 'RestKit/Search', '~> 0.20.0'
pod 'NoticeView', '~> 3.0.7'
pod 'Appirater'
pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage'
pod 'MBProgressHUD'
pod 'DTCoreText'
pod 'QuickDialog', '< 0.9'
pod 'SVPullToRefresh'
pod 'MTStatusBarOverlay'
pod 'WCAlertView'
pod 'ViewDeck'
pod 'OpenUDID'
pod 'MGImageUtilities'
pod 'MCUIImageAdvanced'
pod 'MGBox2'
