platform :ios, '5.0'

pod 'SBJson'
pod 'TouchJSON'
pod 'ZipArchive'
pod 'Reachability', :git => 'https://github.com/tonymillion/Reachability'
pod 'RestKit'
pod 'RestKit/Testing'
pod 'RestKit/Search'
pod 'NoticeView'
pod 'Appirater'
pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage'
pod 'MBProgressHUD'
pod 'DTCoreText'
pod 'QuickDialog', :git => 'https://github.com/escoz/QuickDialog'
pod 'SVPullToRefresh', :git => 'https://github.com/samvermette/SVPullToRefresh'
pod 'MTStatusBarOverlay', :git => 'https://github.com/myell0w/MTStatusBarOverlay'
pod 'ViewDeck', '= 2.2.11' # 'https://github.com/Inferis/ViewDeck'
pod 'OpenUDID'
pod 'MGImageUtilities'
pod 'MCUIImageAdvanced', :git => 'https://github.com/mirego/MCUIImageAdvanced'
pod 'MGBox2'
pod 'EAIntroView'#, :git => 'https://github.com/ealeksandrov/EAIntroView'
